alter table pacientes
add logradouro varchar(255),
add bairro varchar(255),
add telefone varchar(14),
add dataDeNascimento date,
add pessoasResidencia tinyint,
add pessoasResidenciaQueTrabalham tinyint,
add rendaFamilia varchar(255),
add comoConheceu varchar(255);
